### ISSUE TITLE
Rewrite to TypeScript

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#62]
I would like to rewrite the code to TypeScript and modify the build process to emit the lib folder on `build`
- With TypeScript we can identify potential problems and improve the code readability
- The TypeScript declarations will no longer differ from the code in the future, but will be generated natively

I'm interested to create a PR for that

**Comment by pioardi** [comment]
Hi @Shinigami92 ,
Thanks again for all your feedbacks.

This is interesting !!! The only problem here is that I don't know TypeScript so for me could be difficult to mantain the repo. 

Would you provide a small example of the repo in TS so that I can see if I am able to understand the code and mantain It ?
I would love that❤️

Let me know please,
Alessandro

**Comment by Shinigami92** [comment]
Sure I will try to create such an example

**Comment by Shinigami92** [comment]
This isn't the first repo I migrate to TS
I'm happy to also give support if you need it later on
If you want, you can visit my [profile page](https://github.com/Shinigami92) and read my profile readme
